"""
backend/auth.py
------------------
PHASE 2 IMPLEMENTATION.

Wraps Supabase Auth (email/password + Google OAuth + password reset)
behind a small, friendly-error API that streamlit_app.py and
components/landing.py call. Deliberately does NOT reuse LearnMate's
email-lookup "auth" pattern (no custom password table, no email-only
"login") — see PHASE0_AUDIT.md §C.

SESSION MODEL (see PHASE2_ARCHITECTURE_AUDIT.md §6):
st.session_state caches a Supabase-issued session (access_token +
refresh_token); it does NOT invent its own credential. Every page load
that needs to know "is this a real, still-valid session" re-validates
via get_current_user(), which asks the Supabase client for the current
user rather than trusting a locally-set boolean flag.

GOOGLE OAUTH / PKCE:
Supabase's OAuth flow is PKCE: the authorization code that comes back on
the redirect is only redeemable together with the code_verifier that was
generated when the sign-in URL was built. Streamlit reruns the script on
every interaction and the redirect back from Google is a brand-new browser
navigation (new Streamlit session), so the verifier CANNOT live in
st.session_state or in the shared, cached Supabase client. It is therefore
carried through the redirect in a short-lived browser cookie
(_PKCE_COOKIE) and read back on the callback via st.context.cookies. The
verifier itself is still generated by the Supabase client library; this
module only preserves it. See get_google_sign_in_url() and
complete_oauth_from_query_params().
"""

from __future__ import annotations

import os
import re
import time
from dataclasses import dataclass
from urllib.parse import quote, unquote

import streamlit as st

from backend.audit_log import (
    log_event, EVENT_SIGNUP, EVENT_LOGIN, EVENT_LOGIN_FAILED, EVENT_LOGOUT,
    EVENT_PASSWORD_RESET_REQUESTED, EVENT_PROFILE_CREATED,
)
from backend.logging_config import get_logger
from backend.supabase_client import get_user_client, SupabaseNotConfiguredError
from config import GOOGLE_OAUTH_CONFIG, SUPABASE_USER_CONFIG

logger = get_logger(__name__)

SESSION_KEY = "sahay_supabase_session"  # {"access_token", "refresh_token"}

# --- Google OAuth / PKCE carry-over (see module docstring) ---------------
_PKCE_COOKIE = "sahay_pkce_verifier"
_PKCE_COOKIE_MAX_AGE = 900          # seconds; Supabase flow state itself is short-lived
_PKCE_LS_KEY = "sahay_pkce_verifier"  # localStorage twin of the cookie (see _emit_pkce_cookie)
_PKCE_BRIDGE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_pkce_bridge")
_bridge_component = None
_OAUTH_ATTEMPT_KEY = "sahay_oauth_attempt"   # {"url", "verifier", "created"} per Streamlit session
_OAUTH_ATTEMPT_REUSE_SECONDS = 240  # reuse one sign-in URL/verifier across reruns
_VERIFIER_RE = re.compile(r"^[A-Za-z0-9\-._~=+/]{32,256}$")
_OAUTH_FAILED_MSG = "Google Sign-In didn't complete. Please try again."


class AuthError(RuntimeError):
    """A friendly, user-facing auth error. Message is safe to show as-is
    (never contains a raw exception, stack trace, or token)."""


@dataclass(frozen=True)
class AuthUser:
    id: str
    email: str | None


# ---------------------------------------------------------------------------
# Session helpers
# ---------------------------------------------------------------------------

def _client():
    session = st.session_state.get(SESSION_KEY)
    if session:
        return get_user_client(session["access_token"], session["refresh_token"])
    return get_user_client()


def _store_session(auth_response) -> None:
    session = getattr(auth_response, "session", None)
    if session is None:
        return
    st.session_state[SESSION_KEY] = {
        "access_token": session.access_token,
        "refresh_token": session.refresh_token,
    }


def get_current_user() -> AuthUser | None:
    """The single source of truth for "is someone really signed in."
    Re-validates against the Supabase client rather than trusting a
    locally-set boolean — see the module docstring's SESSION MODEL note.
    Returns None (not an exception) when there is no valid session, so
    callers can use it directly in an `if` check."""
    session = st.session_state.get(SESSION_KEY)
    if not session:
        return None
    try:
        client = _client()
        resp = client.auth.get_user(session["access_token"])
        user = getattr(resp, "user", None)
        if user is None:
            return None
        return AuthUser(id=user.id, email=user.email)
    except SupabaseNotConfiguredError:
        raise
    except Exception:  # noqa: BLE001 - any auth-check failure means "not signed in"
        logger.exception("get_current_user: session validation failed")
        return None


def ensure_profile_row(user: AuthUser) -> None:
    """Create a minimal profiles row on first login if one doesn't exist
    yet. Uses the user's OWN anon-key session (not the admin client) —
    the INSERT is covered by the profiles_insert_own RLS policy
    (auth.uid() = id), so this works entirely within RLS."""
    client = _client()
    existing = client.table("profiles").select("id").eq("id", user.id).execute()
    if existing.data:
        return
    client.table("profiles").insert({
        "id": user.id,
        "role": "student",
        "onboarding_complete": False,
    }).execute()
    log_event(actor_type="system", action=EVENT_PROFILE_CREATED, actor_id=user.id)


def get_profile(user: AuthUser) -> dict | None:
    client = _client()
    resp = client.table("profiles").select("*").eq("id", user.id).single().execute()
    return resp.data


def get_client_for_current_user():
    """Public accessor for the current session's RLS-scoped client, for
    pages that need to read/write their own profile data beyond what
    get_profile()/ensure_profile_row() already cover (e.g. profile
    edits). Returns the same client _client() would build internally —
    exposed publicly so callers don't need to reach into a private
    function."""
    return _client()


# ---------------------------------------------------------------------------
# Email / password
# ---------------------------------------------------------------------------

def sign_up(email: str, password: str) -> AuthUser:
    try:
        client = _client()
        resp = client.auth.sign_up({"email": email, "password": password})
    except SupabaseNotConfiguredError:
        raise
    except Exception as exc:
        raise AuthError(_friendly_auth_error(exc)) from exc

    if resp.user is None:
        raise AuthError("Could not create an account with those details. Please try again.")

    _store_session(resp)
    user = AuthUser(id=resp.user.id, email=resp.user.email)
    log_event(actor_type="user", action=EVENT_SIGNUP, actor_id=user.id)
    return user


def sign_in_with_password(email: str, password: str) -> AuthUser:
    try:
        client = _client()
        resp = client.auth.sign_in_with_password({"email": email, "password": password})
    except SupabaseNotConfiguredError:
        raise
    except Exception as exc:
        log_event(actor_type="user", action=EVENT_LOGIN_FAILED, target=_mask_email(email))
        raise AuthError(_friendly_auth_error(exc)) from exc

    if resp.user is None:
        log_event(actor_type="user", action=EVENT_LOGIN_FAILED, target=_mask_email(email))
        raise AuthError("Incorrect email or password.")

    _store_session(resp)
    user = AuthUser(id=resp.user.id, email=resp.user.email)
    ensure_profile_row(user)
    log_event(actor_type="user", action=EVENT_LOGIN, actor_id=user.id)
    return user


def reset_password_for_email(email: str) -> None:
    """Sends a password-reset email via Supabase. Always returns silently
    (Supabase itself decides whether the email exists — this function
    never reveals that to the caller, avoiding an email-enumeration
    side-channel)."""
    try:
        client = _client()
        client.auth.reset_password_for_email(email)
    except SupabaseNotConfiguredError:
        raise
    except Exception:
        logger.exception("reset_password_for_email failed")
        # Deliberately no re-raise with detail — see docstring.
    log_event(actor_type="user", action=EVENT_PASSWORD_RESET_REQUESTED, target=_mask_email(email))


# ---------------------------------------------------------------------------
# Google OAuth
# ---------------------------------------------------------------------------

class _PkceStorage:
    """Minimal in-memory storage object handed to a throw-away Supabase
    client. It (a) lets us capture the code verifier the library generates
    when it builds the OAuth URL, and (b) lets us give that same verifier
    back to a fresh client when exchanging the code. The library only ever
    asks for the key ending in "-code-verifier", so we match on the suffix
    instead of hard-coding the library's storage-key format."""

    _SUFFIX = "-code-verifier"

    def __init__(self, verifier: str | None = None) -> None:
        self._data: dict[str, str] = {}
        self._verifier = verifier

    def get_item(self, key: str):
        if key.endswith(self._SUFFIX) and self._verifier:
            return self._verifier
        return self._data.get(key)

    def set_item(self, key: str, value: str) -> None:
        self._data[key] = value

    def remove_item(self, key: str) -> None:
        self._data.pop(key, None)

    def captured_verifier(self) -> str | None:
        for key, value in self._data.items():
            if key.endswith(self._SUFFIX):
                return value
        return None


def _new_pkce_client(storage: _PkceStorage):
    """A fresh, un-cached anon-key client for ONE OAuth attempt, using the
    caller's private storage. Never shared between visitors and never
    holds a user session."""
    from supabase import create_client
    try:
        from supabase import ClientOptions
    except ImportError:  # older/newer supabase-py layouts
        try:
            from supabase.client import ClientOptions
        except ImportError:
            from supabase.lib.client_options import ClientOptions
    options = ClientOptions(
        storage=storage,
        flow_type="pkce",
        auto_refresh_token=False,
        persist_session=False,
    )
    return create_client(SUPABASE_USER_CONFIG.url, SUPABASE_USER_CONFIG.anon_key, options=options)


def _get_bridge():
    """Lazily declares the zero-height bridge component (backend/_pkce_bridge).
    Returns None if it can't be declared, so callers degrade to cookie-only."""
    global _bridge_component
    if _bridge_component is None:
        try:
            import streamlit.components.v1 as components
            _bridge_component = components.declare_component("sahay_pkce_bridge", path=_PKCE_BRIDGE_DIR)
        except Exception:  # noqa: BLE001
            logger.exception("PKCE bridge component unavailable")
            return None
    return _bridge_component


def _emit_pkce_cookie(verifier: str) -> None:
    """Stores the verifier in the BROWSER so it survives the redirect to
    Google and back. Two copies: a short-lived cookie (works wherever the host
    forwards cookies to Streamlit) and a localStorage entry written by the
    bridge component. On Streamlit Community Cloud the cookie often never
    reaches st.context.cookies, so the callback falls back to localStorage.
    Both stay bound to THIS browser, which is what PKCE needs."""
    if not _VERIFIER_RE.match(verifier):
        raise AuthError("Google Sign-In couldn't be started. Please try again.")
    value = quote(verifier, safe="")
    js = (
        "<script>(function(){try{"
        "var d=document;"
        "try{if(window.parent&&window.parent!==window&&window.parent.document){d=window.parent.document;}}catch(e){}"
        "var sec=(d.location.protocol==='https:')?'; Secure':'';"
        f"d.cookie='{_PKCE_COOKIE}={value}; Max-Age={_PKCE_COOKIE_MAX_AGE}; Path=/; SameSite=Lax'+sec;"
        "}catch(e){}})();</script>"
    )
    try:
        st.html(js, unsafe_allow_javascript=True)  # Streamlit >= 1.52
    except TypeError:
        import streamlit.components.v1 as components  # older Streamlit
        components.html(js, height=0)
    bridge = _get_bridge()
    if bridge is not None:
        bridge(mode="store", verifier=verifier, key="sahay_pkce_store", default=None)


def _read_verifier_from_browser() -> str | None:
    """Callback-time fallback when the cookie didn't arrive. Renders the
    bridge component in read mode. Returns None while waiting for the browser
    to answer (the component's reply triggers a rerun), "" if the browser had
    nothing usable, else the verifier."""
    bridge = _get_bridge()
    if bridge is None:
        return ""
    got = bridge(mode="read", ttl_ms=_PKCE_COOKIE_MAX_AGE * 1000, key="sahay_pkce_read", default=None)
    if got is None:
        return None
    if isinstance(got, str) and got != "missing" and _VERIFIER_RE.match(got):
        return got
    return ""


def _read_pkce_cookie() -> str | None:
    try:
        raw = st.context.cookies.get(_PKCE_COOKIE)
    except Exception:  # noqa: BLE001 - st.context missing on very old Streamlit
        return None
    return unquote(raw) if raw else None


def get_google_sign_in_url() -> str:
    """Builds the Supabase-hosted Google OAuth URL to redirect the user to,
    and stores the matching PKCE code verifier in this browser's cookie.

    One URL/verifier pair is created per Streamlit session and reused across
    reruns (refreshed after _OAUTH_ATTEMPT_REUSE_SECONDS), so the link the
    user clicks always matches the cookie in their browser. Requires
    GOOGLE_OAUTH_CONFIG.is_configured and SUPABASE_USER_CONFIG.is_configured;
    raises AuthError with a clear message if either is missing.
    """
    if not SUPABASE_USER_CONFIG.is_configured:
        raise AuthError("Google Sign-In isn't configured yet — Supabase connection is missing.")
    if not GOOGLE_OAUTH_CONFIG.is_configured:
        raise AuthError("Google Sign-In isn't configured yet — Google OAuth settings are missing.")

    attempt = st.session_state.get(_OAUTH_ATTEMPT_KEY)
    if not attempt or time.time() - attempt["created"] > _OAUTH_ATTEMPT_REUSE_SECONDS:
        storage = _PkceStorage()
        try:
            client = _new_pkce_client(storage)
            resp = client.auth.sign_in_with_oauth({
                "provider": "google",
                "options": {"redirect_to": GOOGLE_OAUTH_CONFIG.redirect_url},
            })
        except SupabaseNotConfiguredError:
            raise
        except Exception as exc:  # noqa: BLE001
            logger.exception("Google sign-in URL creation failed")
            raise AuthError("Google Sign-In couldn't be started. Please try again.") from exc
        verifier = storage.captured_verifier()
        if not verifier:
            logger.error("sign_in_with_oauth returned a URL but no PKCE code verifier was stored")
            raise AuthError("Google Sign-In couldn't be started. Please try again.")
        attempt = {"url": resp.url, "verifier": verifier, "created": time.time()}
        st.session_state[_OAUTH_ATTEMPT_KEY] = attempt

    _emit_pkce_cookie(attempt["verifier"])
    return attempt["url"]


def complete_oauth_from_query_params() -> AuthUser | None:
    """Call once near the top of the app on every load. If the URL query
    params contain an OAuth callback code (i.e. the user was just
    redirected back from Google via Supabase), exchanges it — together with
    the PKCE verifier from this browser's cookie — for a session.
    Returns None (no-op) on any normal page load with no callback present.

    The code is single-use, so the query params are ALWAYS cleared here,
    success or failure; otherwise every Streamlit rerun would resubmit the
    same dead code and Supabase would answer "flow state has expired".
    """
    params = st.query_params
    code = params.get("code")
    if not code:
        return None

    # Preferred source: the browser cookie. Fallback (Streamlit Community
    # Cloud often drops it): the localStorage bridge component.
    verifier = _read_pkce_cookie()
    if not verifier:
        logger.info("OAuth callback: no verifier cookie; reading from browser localStorage")
        browser_value = _read_verifier_from_browser()
        if browser_value is None:
            st.caption("Completing sign-in\u2026")
            st.stop()  # query params stay intact; the component's reply reruns the script
        verifier = browser_value or None

    try:
        if not verifier:
            logger.error("OAuth callback received but no PKCE verifier (cookie or localStorage) was available")
            raise AuthError(_OAUTH_FAILED_MSG)

        try:
            client = _new_pkce_client(_PkceStorage(verifier=verifier))
            resp = client.auth.exchange_code_for_session({
                "auth_code": code,
                "code_verifier": verifier,
            })
        except SupabaseNotConfiguredError:
            raise
        except Exception as exc:
            logger.exception("OAuth callback exchange failed")
            raise AuthError(_OAUTH_FAILED_MSG) from exc

        if resp.user is None:
            raise AuthError(_OAUTH_FAILED_MSG)

        _store_session(resp)
        user = AuthUser(id=resp.user.id, email=resp.user.email)
        ensure_profile_row(user)
        log_event(actor_type="user", action=EVENT_LOGIN, actor_id=user.id, target="google_oauth")
        st.session_state.pop(_OAUTH_ATTEMPT_KEY, None)
        return user
    finally:
        st.query_params.clear()


# ---------------------------------------------------------------------------
# Sign out
# ---------------------------------------------------------------------------

def sign_out() -> None:
    """Real sign-out: invalidates the refresh token server-side via
    Supabase, THEN clears local session state. Order matters — clearing
    local state first and letting the server call fail silently would
    leave a still-valid token the app just forgot about."""
    user = get_current_user()
    try:
        client = _client()
        client.auth.sign_out()
    except Exception:
        logger.exception("sign_out: Supabase sign_out call failed (clearing local session anyway)")
    finally:
        st.session_state.pop(SESSION_KEY, None)
    if user:
        log_event(actor_type="user", action=EVENT_LOGOUT, actor_id=user.id)


# ---------------------------------------------------------------------------
# Error message mapping — never leak raw exception text to the user
# ---------------------------------------------------------------------------

def _friendly_auth_error(exc: Exception) -> str:
    text = str(exc).lower()
    if "already registered" in text or "already exists" in text or "duplicate" in text:
        return "An account with that email already exists. Try logging in instead."
    if "invalid login credentials" in text or "invalid email or password" in text:
        return "Incorrect email or password."
    if "password" in text and ("short" in text or "weak" in text or "least" in text):
        return "That password doesn't meet the minimum requirements. Please choose a longer password."
    if "rate limit" in text or "too many" in text:
        return "Too many attempts. Please wait a moment and try again."
    if "network" in text or "timeout" in text or "connection" in text:
        return "Couldn't reach the authentication service. Please check your connection and try again."
    logger.warning("Unmapped auth error (showing generic message to user): %r", exc)
    return "Something went wrong signing you in. Please try again."


def _mask_email(email: str) -> str:
    """For audit_log `target` only — never store a full email verbatim in
    a security log we intend to keep readable without becoming a second
    copy of user PII."""
    if "@" not in email:
        return "***"
    local, _, domain = email.partition("@")
    masked_local = (local[0] + "***") if local else "***"
    return f"{masked_local}@{domain}"
